/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionProcedureRouteImport } from './routes/admission-procedure'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ApplyOnlineRouteImport } from './routes/apply-online'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DigitalLearningRouteImport } from './routes/digital-learning'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as ExaminationsRouteImport } from './routes/examinations'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FindACampusRouteImport } from './routes/find-a-campus'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as FutureSkillsRouteImport } from './routes/future-skills'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LearnToEarnRouteImport } from './routes/learn-to-earn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsEventsRouteImport } from './routes/news-events'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SteamRouteImport } from './routes/steam'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as StudentWellbeingRouteImport } from './routes/student-wellbeing'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeacherDevelopmentRouteImport } from './routes/teacher-development'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAlumniRouteImport } from './routes/about.alumni'
import { Route as AboutAtAGlanceRouteImport } from './routes/about.at-a-glance'
import { Route as AboutChairpersonRouteImport } from './routes/about.chairperson'
import { Route as AboutEducationalPhilosophyRouteImport } from './routes/about.educational-philosophy'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutNewsEventsRouteImport } from './routes/about.news-events'
import { Route as AboutNoticesRouteImport } from './routes/about.notices'
import { Route as AboutOurStoryRouteImport } from './routes/about.our-story'
import { Route as AboutSignatureSchoolRouteImport } from './routes/about.signature-school'
import { Route as AboutTeacherTrainingRouteImport } from './routes/about.teacher-training'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as ApiSendDigestRouteImport } from './routes/api/send-digest'
import { Route as CareersApplyRouteImport } from './routes/careers.apply'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardCmsRouteImport } from './routes/dashboard.cms'
import { Route as DashboardForgotPasswordRouteImport } from './routes/dashboard.forgot-password'
import { Route as DashboardInstructorRouteImport } from './routes/dashboard.instructor'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardResetPasswordRouteImport } from './routes/dashboard.reset-password'
import { Route as DashboardSchoolRouteImport } from './routes/dashboard.school'
import { Route as DashboardSignupRouteImport } from './routes/dashboard.signup'
import { Route as DigitalSchoolParentPortalRouteImport } from './routes/digital-school.parent-portal'
import { Route as DigitalSchoolStudentPortalRouteImport } from './routes/digital-school.student-portal'
import { Route as DigitalSchoolTeacherPortalRouteImport } from './routes/digital-school.teacher-portal'
import { Route as FranchiseApplyRouteImport } from './routes/franchise.apply'
import { Route as NewsEventsIndexRouteImport } from './routes/news-events.index'
import { Route as NewsEventsSlugRouteImport } from './routes/news-events.$slug'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportTicketsRouteImport } from './routes/support.tickets'
import { Route as AboutNoticesIndexRouteImport } from './routes/about.notices.index'
import { Route as AboutNoticesNoticeIdRouteImport } from './routes/about.notices.$noticeId'
import { Route as AcademicsCalendarIdRouteImport } from './routes/academics.calendar.$id'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminAuditLogRouteImport } from './routes/dashboard.admin.audit-log'
import { Route as DashboardAdminOverviewRouteImport } from './routes/dashboard.admin.overview'
import { Route as DashboardAdminPromotionRouteImport } from './routes/dashboard.admin.promotion'
import { Route as DashboardAdminSessionsRouteImport } from './routes/dashboard.admin.sessions'
import { Route as DashboardAdminSiteRouteImport } from './routes/dashboard.admin.site'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminSubmissionsRouteImport } from './routes/dashboard.admin.submissions'
import { Route as DashboardAdminTermsRouteImport } from './routes/dashboard.admin.terms'
import { Route as DashboardAdminWhitelistRouteImport } from './routes/dashboard.admin.whitelist'
import { Route as DashboardCmsIndexRouteImport } from './routes/dashboard.cms.index'
import { Route as DashboardInstructorIndexRouteImport } from './routes/dashboard.instructor.index'
import { Route as DashboardSchoolIndexRouteImport } from './routes/dashboard.school.index'
import { Route as DashboardSchoolInvoicesRouteImport } from './routes/dashboard.school.invoices'
import { Route as DashboardSchoolSummaryRouteImport } from './routes/dashboard.school.summary'
import { Route as DashboardAdminInstructorsIndexRouteImport } from './routes/dashboard.admin.instructors.index'
import { Route as DashboardAdminInstructorsInstructorEmailRouteImport } from './routes/dashboard.admin.instructors.$instructorEmail'
import { Route as DashboardAdminInvoicesIndexRouteImport } from './routes/dashboard.admin.invoices.index'
import { Route as DashboardAdminInvoicesInvoiceIdRouteImport } from './routes/dashboard.admin.invoices.$invoiceId'
import { Route as DashboardAdminSchoolsIndexRouteImport } from './routes/dashboard.admin.schools.index'
import { Route as DashboardAdminStudentStudentIdRouteImport } from './routes/dashboard.admin.student.$studentId'
import { Route as DashboardInstructorSectionSectionIdRouteImport } from './routes/dashboard.instructor.section.$sectionId'
import { Route as DashboardInstructorStudentStudentIdRouteImport } from './routes/dashboard.instructor.student.$studentId'
import { Route as DashboardSchoolSectionSectionIdRouteImport } from './routes/dashboard.school.section.$sectionId'
import { Route as DashboardSchoolStudentStudentIdRouteImport } from './routes/dashboard.school.student.$studentId'
import { Route as DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport } from './routes/dashboard.admin.schools.$schoolId.sections.index'
import { Route as DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport } from './routes/dashboard.admin.schools.$schoolId.sections.$sectionId.sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionProcedureRoute = AdmissionProcedureRouteImport.update({
  id: '/admission-procedure',
  path: '/admission-procedure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyOnlineRoute = ApplyOnlineRouteImport.update({
  id: '/apply-online',
  path: '/apply-online',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalLearningRoute = DigitalLearningRouteImport.update({
  id: '/digital-learning',
  path: '/digital-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsRoute = ExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FindACampusRoute = FindACampusRouteImport.update({
  id: '/find-a-campus',
  path: '/find-a-campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureSkillsRoute = FutureSkillsRouteImport.update({
  id: '/future-skills',
  path: '/future-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnToEarnRoute = LearnToEarnRouteImport.update({
  id: '/learn-to-earn',
  path: '/learn-to-earn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SteamRoute = SteamRouteImport.update({
  id: '/steam',
  path: '/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWellbeingRoute = StudentWellbeingRouteImport.update({
  id: '/student-wellbeing',
  path: '/student-wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDevelopmentRoute = TeacherDevelopmentRouteImport.update({
  id: '/teacher-development',
  path: '/teacher-development',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAlumniRoute = AboutAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAtAGlanceRoute = AboutAtAGlanceRouteImport.update({
  id: '/at-a-glance',
  path: '/at-a-glance',
  getParentRoute: () => AboutRoute,
} as any)
const AboutChairpersonRoute = AboutChairpersonRouteImport.update({
  id: '/chairperson',
  path: '/chairperson',
  getParentRoute: () => AboutRoute,
} as any)
const AboutEducationalPhilosophyRoute =
  AboutEducationalPhilosophyRouteImport.update({
    id: '/educational-philosophy',
    path: '/educational-philosophy',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutNewsEventsRoute = AboutNewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => AboutRoute,
} as any)
const AboutNoticesRoute = AboutNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSignatureSchoolRoute = AboutSignatureSchoolRouteImport.update({
  id: '/signature-school',
  path: '/signature-school',
  getParentRoute: () => AboutRoute,
} as any)
const AboutTeacherTrainingRoute = AboutTeacherTrainingRouteImport.update({
  id: '/teacher-training',
  path: '/teacher-training',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => AboutRoute,
} as any)
const ApiSendDigestRoute = ApiSendDigestRouteImport.update({
  id: '/api/send-digest',
  path: '/api/send-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCmsRoute = DashboardCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForgotPasswordRoute = DashboardForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstructorRoute = DashboardInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResetPasswordRoute = DashboardResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchoolRoute = DashboardSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignupRoute = DashboardSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DashboardRoute,
} as any)
const DigitalSchoolParentPortalRoute =
  DigitalSchoolParentPortalRouteImport.update({
    id: '/digital-school/parent-portal',
    path: '/digital-school/parent-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalSchoolStudentPortalRoute =
  DigitalSchoolStudentPortalRouteImport.update({
    id: '/digital-school/student-portal',
    path: '/digital-school/student-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalSchoolTeacherPortalRoute =
  DigitalSchoolTeacherPortalRouteImport.update({
    id: '/digital-school/teacher-portal',
    path: '/digital-school/teacher-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const FranchiseApplyRoute = FranchiseApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => FranchiseRoute,
} as any)
const NewsEventsIndexRoute = NewsEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsEventsRoute,
} as any)
const NewsEventsSlugRoute = NewsEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsEventsRoute,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SupportTicketsRoute = SupportTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => SupportRoute,
} as any)
const AboutNoticesIndexRoute = AboutNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutNoticesRoute,
} as any)
const AboutNoticesNoticeIdRoute = AboutNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => AboutNoticesRoute,
} as any)
const AcademicsCalendarIdRoute = AcademicsCalendarIdRouteImport.update({
  id: '/calendar/$id',
  path: '/calendar/$id',
  getParentRoute: () => AcademicsRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAuditLogRoute = DashboardAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminOverviewRoute = DashboardAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPromotionRoute = DashboardAdminPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSessionsRoute = DashboardAdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSiteRoute = DashboardAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSubmissionsRoute =
  DashboardAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminTermsRoute = DashboardAdminTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminWhitelistRoute = DashboardAdminWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardCmsIndexRoute = DashboardCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCmsRoute,
} as any)
const DashboardInstructorIndexRoute =
  DashboardInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardSchoolIndexRoute = DashboardSchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardSchoolInvoicesRoute = DashboardSchoolInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardSchoolSummaryRoute = DashboardSchoolSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardAdminInstructorsIndexRoute =
  DashboardAdminInstructorsIndexRouteImport.update({
    id: '/instructors/',
    path: '/instructors/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInstructorsInstructorEmailRoute =
  DashboardAdminInstructorsInstructorEmailRouteImport.update({
    id: '/instructors/$instructorEmail',
    path: '/instructors/$instructorEmail',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInvoicesIndexRoute =
  DashboardAdminInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInvoicesInvoiceIdRoute =
  DashboardAdminInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSchoolsIndexRoute =
  DashboardAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminStudentStudentIdRoute =
  DashboardAdminStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardInstructorSectionSectionIdRoute =
  DashboardInstructorSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardInstructorStudentStudentIdRoute =
  DashboardInstructorStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardSchoolSectionSectionIdRoute =
  DashboardSchoolSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => DashboardSchoolRoute,
  } as any)
const DashboardSchoolStudentStudentIdRoute =
  DashboardSchoolStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardSchoolRoute,
  } as any)
const DashboardAdminSchoolsSchoolIdSectionsIndexRoute =
  DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport.update({
    id: '/schools/$schoolId/sections/',
    path: '/schools/$schoolId/sections/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute =
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport.update({
    id: '/schools/$schoolId/sections/$sectionId/sessions',
    path: '/schools/$schoolId/sections/$sectionId/sessions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/admission-procedure': typeof AdmissionProcedureRoute
  '/admissions': typeof AdmissionsRoute
  '/apply-online': typeof ApplyOnlineRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/digital-learning': typeof DigitalLearningRoute
  '/email-preview': typeof EmailPreviewRoute
  '/examinations': typeof ExaminationsRoute
  '/faqs': typeof FaqsRoute
  '/find-a-campus': typeof FindACampusRoute
  '/for-schools': typeof ForSchoolsRoute
  '/franchise': typeof FranchiseRouteWithChildren
  '/future-skills': typeof FutureSkillsRoute
  '/leadership': typeof LeadershipRoute
  '/learn-to-earn': typeof LearnToEarnRoute
  '/login': typeof LoginRoute
  '/news-events': typeof NewsEventsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRoute
  '/steam': typeof SteamRoute
  '/student-life': typeof StudentLifeRoute
  '/student-wellbeing': typeof StudentWellbeingRoute
  '/students': typeof StudentsRoute
  '/support': typeof SupportRouteWithChildren
  '/teacher-development': typeof TeacherDevelopmentRoute
  '/about/alumni': typeof AboutAlumniRoute
  '/about/at-a-glance': typeof AboutAtAGlanceRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/news-events': typeof AboutNewsEventsRoute
  '/about/notices': typeof AboutNoticesRouteWithChildren
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/signature-school': typeof AboutSignatureSchoolRoute
  '/about/teacher-training': typeof AboutTeacherTrainingRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/careers/apply': typeof CareersApplyRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteWithChildren
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/instructor': typeof DashboardInstructorRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/school': typeof DashboardSchoolRouteWithChildren
  '/dashboard/signup': typeof DashboardSignupRoute
  '/digital-school/parent-portal': typeof DigitalSchoolParentPortalRoute
  '/digital-school/student-portal': typeof DigitalSchoolStudentPortalRoute
  '/digital-school/teacher-portal': typeof DigitalSchoolTeacherPortalRoute
  '/franchise/apply': typeof FranchiseApplyRoute
  '/news-events/$slug': typeof NewsEventsSlugRoute
  '/support/tickets': typeof SupportTicketsRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news-events/': typeof NewsEventsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/about/notices/$noticeId': typeof AboutNoticesNoticeIdRoute
  '/academics/calendar/$id': typeof AcademicsCalendarIdRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/about/notices/': typeof AboutNoticesIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/instructor/': typeof DashboardInstructorIndexRoute
  '/dashboard/school/': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors/': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices/': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools/': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admission-procedure': typeof AdmissionProcedureRoute
  '/admissions': typeof AdmissionsRoute
  '/apply-online': typeof ApplyOnlineRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/digital-learning': typeof DigitalLearningRoute
  '/email-preview': typeof EmailPreviewRoute
  '/examinations': typeof ExaminationsRoute
  '/faqs': typeof FaqsRoute
  '/find-a-campus': typeof FindACampusRoute
  '/for-schools': typeof ForSchoolsRoute
  '/franchise': typeof FranchiseRouteWithChildren
  '/future-skills': typeof FutureSkillsRoute
  '/leadership': typeof LeadershipRoute
  '/learn-to-earn': typeof LearnToEarnRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRoute
  '/steam': typeof SteamRoute
  '/student-life': typeof StudentLifeRoute
  '/student-wellbeing': typeof StudentWellbeingRoute
  '/students': typeof StudentsRoute
  '/teacher-development': typeof TeacherDevelopmentRoute
  '/about/alumni': typeof AboutAlumniRoute
  '/about/at-a-glance': typeof AboutAtAGlanceRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/news-events': typeof AboutNewsEventsRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/signature-school': typeof AboutSignatureSchoolRoute
  '/about/teacher-training': typeof AboutTeacherTrainingRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/careers/apply': typeof CareersApplyRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/digital-school/parent-portal': typeof DigitalSchoolParentPortalRoute
  '/digital-school/student-portal': typeof DigitalSchoolStudentPortalRoute
  '/digital-school/teacher-portal': typeof DigitalSchoolTeacherPortalRoute
  '/franchise/apply': typeof FranchiseApplyRoute
  '/news-events/$slug': typeof NewsEventsSlugRoute
  '/support/tickets': typeof SupportTicketsRoute
  '/about': typeof AboutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/news-events': typeof NewsEventsIndexRoute
  '/support': typeof SupportIndexRoute
  '/about/notices/$noticeId': typeof AboutNoticesNoticeIdRoute
  '/academics/calendar/$id': typeof AcademicsCalendarIdRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/about/notices': typeof AboutNoticesIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/cms': typeof DashboardCmsIndexRoute
  '/dashboard/instructor': typeof DashboardInstructorIndexRoute
  '/dashboard/school': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/admission-procedure': typeof AdmissionProcedureRoute
  '/admissions': typeof AdmissionsRoute
  '/apply-online': typeof ApplyOnlineRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/digital-learning': typeof DigitalLearningRoute
  '/email-preview': typeof EmailPreviewRoute
  '/examinations': typeof ExaminationsRoute
  '/faqs': typeof FaqsRoute
  '/find-a-campus': typeof FindACampusRoute
  '/for-schools': typeof ForSchoolsRoute
  '/franchise': typeof FranchiseRouteWithChildren
  '/future-skills': typeof FutureSkillsRoute
  '/leadership': typeof LeadershipRoute
  '/learn-to-earn': typeof LearnToEarnRoute
  '/login': typeof LoginRoute
  '/news-events': typeof NewsEventsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRoute
  '/steam': typeof SteamRoute
  '/student-life': typeof StudentLifeRoute
  '/student-wellbeing': typeof StudentWellbeingRoute
  '/students': typeof StudentsRoute
  '/support': typeof SupportRouteWithChildren
  '/teacher-development': typeof TeacherDevelopmentRoute
  '/about/alumni': typeof AboutAlumniRoute
  '/about/at-a-glance': typeof AboutAtAGlanceRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/news-events': typeof AboutNewsEventsRoute
  '/about/notices': typeof AboutNoticesRouteWithChildren
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/signature-school': typeof AboutSignatureSchoolRoute
  '/about/teacher-training': typeof AboutTeacherTrainingRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/careers/apply': typeof CareersApplyRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteWithChildren
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/instructor': typeof DashboardInstructorRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/school': typeof DashboardSchoolRouteWithChildren
  '/dashboard/signup': typeof DashboardSignupRoute
  '/digital-school/parent-portal': typeof DigitalSchoolParentPortalRoute
  '/digital-school/student-portal': typeof DigitalSchoolStudentPortalRoute
  '/digital-school/teacher-portal': typeof DigitalSchoolTeacherPortalRoute
  '/franchise/apply': typeof FranchiseApplyRoute
  '/news-events/$slug': typeof NewsEventsSlugRoute
  '/support/tickets': typeof SupportTicketsRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news-events/': typeof NewsEventsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/about/notices/$noticeId': typeof AboutNoticesNoticeIdRoute
  '/academics/calendar/$id': typeof AcademicsCalendarIdRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/about/notices/': typeof AboutNoticesIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/instructor/': typeof DashboardInstructorIndexRoute
  '/dashboard/school/': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors/': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices/': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools/': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admission-procedure'
    | '/admissions'
    | '/apply-online'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/digital-learning'
    | '/email-preview'
    | '/examinations'
    | '/faqs'
    | '/find-a-campus'
    | '/for-schools'
    | '/franchise'
    | '/future-skills'
    | '/leadership'
    | '/learn-to-earn'
    | '/login'
    | '/news-events'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/school'
    | '/schools'
    | '/steam'
    | '/student-life'
    | '/student-wellbeing'
    | '/students'
    | '/support'
    | '/teacher-development'
    | '/about/alumni'
    | '/about/at-a-glance'
    | '/about/chairperson'
    | '/about/educational-philosophy'
    | '/about/leadership'
    | '/about/news-events'
    | '/about/notices'
    | '/about/our-story'
    | '/about/signature-school'
    | '/about/teacher-training'
    | '/about/vision-mission'
    | '/api/send-digest'
    | '/careers/apply'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/forgot-password'
    | '/dashboard/instructor'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/school'
    | '/dashboard/signup'
    | '/digital-school/parent-portal'
    | '/digital-school/student-portal'
    | '/digital-school/teacher-portal'
    | '/franchise/apply'
    | '/news-events/$slug'
    | '/support/tickets'
    | '/about/'
    | '/dashboard/'
    | '/news-events/'
    | '/support/'
    | '/about/notices/$noticeId'
    | '/academics/calendar/$id'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/about/notices/'
    | '/dashboard/admin/'
    | '/dashboard/cms/'
    | '/dashboard/instructor/'
    | '/dashboard/school/'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors/'
    | '/dashboard/admin/invoices/'
    | '/dashboard/admin/schools/'
    | '/dashboard/admin/schools/$schoolId/sections/'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admission-procedure'
    | '/admissions'
    | '/apply-online'
    | '/careers'
    | '/contact'
    | '/digital-learning'
    | '/email-preview'
    | '/examinations'
    | '/faqs'
    | '/find-a-campus'
    | '/for-schools'
    | '/franchise'
    | '/future-skills'
    | '/leadership'
    | '/learn-to-earn'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/school'
    | '/schools'
    | '/steam'
    | '/student-life'
    | '/student-wellbeing'
    | '/students'
    | '/teacher-development'
    | '/about/alumni'
    | '/about/at-a-glance'
    | '/about/chairperson'
    | '/about/educational-philosophy'
    | '/about/leadership'
    | '/about/news-events'
    | '/about/our-story'
    | '/about/signature-school'
    | '/about/teacher-training'
    | '/about/vision-mission'
    | '/api/send-digest'
    | '/careers/apply'
    | '/dashboard/account'
    | '/dashboard/forgot-password'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/signup'
    | '/digital-school/parent-portal'
    | '/digital-school/student-portal'
    | '/digital-school/teacher-portal'
    | '/franchise/apply'
    | '/news-events/$slug'
    | '/support/tickets'
    | '/about'
    | '/dashboard'
    | '/news-events'
    | '/support'
    | '/about/notices/$noticeId'
    | '/academics/calendar/$id'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/about/notices'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/instructor'
    | '/dashboard/school'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors'
    | '/dashboard/admin/invoices'
    | '/dashboard/admin/schools'
    | '/dashboard/admin/schools/$schoolId/sections'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admission-procedure'
    | '/admissions'
    | '/apply-online'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/digital-learning'
    | '/email-preview'
    | '/examinations'
    | '/faqs'
    | '/find-a-campus'
    | '/for-schools'
    | '/franchise'
    | '/future-skills'
    | '/leadership'
    | '/learn-to-earn'
    | '/login'
    | '/news-events'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/school'
    | '/schools'
    | '/steam'
    | '/student-life'
    | '/student-wellbeing'
    | '/students'
    | '/support'
    | '/teacher-development'
    | '/about/alumni'
    | '/about/at-a-glance'
    | '/about/chairperson'
    | '/about/educational-philosophy'
    | '/about/leadership'
    | '/about/news-events'
    | '/about/notices'
    | '/about/our-story'
    | '/about/signature-school'
    | '/about/teacher-training'
    | '/about/vision-mission'
    | '/api/send-digest'
    | '/careers/apply'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/forgot-password'
    | '/dashboard/instructor'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/school'
    | '/dashboard/signup'
    | '/digital-school/parent-portal'
    | '/digital-school/student-portal'
    | '/digital-school/teacher-portal'
    | '/franchise/apply'
    | '/news-events/$slug'
    | '/support/tickets'
    | '/about/'
    | '/dashboard/'
    | '/news-events/'
    | '/support/'
    | '/about/notices/$noticeId'
    | '/academics/calendar/$id'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/about/notices/'
    | '/dashboard/admin/'
    | '/dashboard/cms/'
    | '/dashboard/instructor/'
    | '/dashboard/school/'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors/'
    | '/dashboard/admin/invoices/'
    | '/dashboard/admin/schools/'
    | '/dashboard/admin/schools/$schoolId/sections/'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AdmissionProcedureRoute: typeof AdmissionProcedureRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ApplyOnlineRoute: typeof ApplyOnlineRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DigitalLearningRoute: typeof DigitalLearningRoute
  EmailPreviewRoute: typeof EmailPreviewRoute
  ExaminationsRoute: typeof ExaminationsRoute
  FaqsRoute: typeof FaqsRoute
  FindACampusRoute: typeof FindACampusRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  FranchiseRoute: typeof FranchiseRouteWithChildren
  FutureSkillsRoute: typeof FutureSkillsRoute
  LeadershipRoute: typeof LeadershipRoute
  LearnToEarnRoute: typeof LearnToEarnRoute
  LoginRoute: typeof LoginRoute
  NewsEventsRoute: typeof NewsEventsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ProjectsRoute: typeof ProjectsRoute
  SchoolRoute: typeof SchoolRoute
  SchoolsRoute: typeof SchoolsRoute
  SteamRoute: typeof SteamRoute
  StudentLifeRoute: typeof StudentLifeRoute
  StudentWellbeingRoute: typeof StudentWellbeingRoute
  StudentsRoute: typeof StudentsRoute
  SupportRoute: typeof SupportRouteWithChildren
  TeacherDevelopmentRoute: typeof TeacherDevelopmentRoute
  ApiSendDigestRoute: typeof ApiSendDigestRoute
  DigitalSchoolParentPortalRoute: typeof DigitalSchoolParentPortalRoute
  DigitalSchoolStudentPortalRoute: typeof DigitalSchoolStudentPortalRoute
  DigitalSchoolTeacherPortalRoute: typeof DigitalSchoolTeacherPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-procedure': {
      id: '/admission-procedure'
      path: '/admission-procedure'
      fullPath: '/admission-procedure'
      preLoaderRoute: typeof AdmissionProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-online': {
      id: '/apply-online'
      path: '/apply-online'
      fullPath: '/apply-online'
      preLoaderRoute: typeof ApplyOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-learning': {
      id: '/digital-learning'
      path: '/digital-learning'
      fullPath: '/digital-learning'
      preLoaderRoute: typeof DigitalLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations': {
      id: '/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof ExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-campus': {
      id: '/find-a-campus'
      path: '/find-a-campus'
      fullPath: '/find-a-campus'
      preLoaderRoute: typeof FindACampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-skills': {
      id: '/future-skills'
      path: '/future-skills'
      fullPath: '/future-skills'
      preLoaderRoute: typeof FutureSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-to-earn': {
      id: '/learn-to-earn'
      path: '/learn-to-earn'
      fullPath: '/learn-to-earn'
      preLoaderRoute: typeof LearnToEarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events': {
      id: '/news-events'
      path: '/news-events'
      fullPath: '/news-events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steam': {
      id: '/steam'
      path: '/steam'
      fullPath: '/steam'
      preLoaderRoute: typeof SteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-wellbeing': {
      id: '/student-wellbeing'
      path: '/student-wellbeing'
      fullPath: '/student-wellbeing'
      preLoaderRoute: typeof StudentWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-development': {
      id: '/teacher-development'
      path: '/teacher-development'
      fullPath: '/teacher-development'
      preLoaderRoute: typeof TeacherDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/alumni': {
      id: '/about/alumni'
      path: '/alumni'
      fullPath: '/about/alumni'
      preLoaderRoute: typeof AboutAlumniRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/at-a-glance': {
      id: '/about/at-a-glance'
      path: '/at-a-glance'
      fullPath: '/about/at-a-glance'
      preLoaderRoute: typeof AboutAtAGlanceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/chairperson': {
      id: '/about/chairperson'
      path: '/chairperson'
      fullPath: '/about/chairperson'
      preLoaderRoute: typeof AboutChairpersonRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/educational-philosophy': {
      id: '/about/educational-philosophy'
      path: '/educational-philosophy'
      fullPath: '/about/educational-philosophy'
      preLoaderRoute: typeof AboutEducationalPhilosophyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/news-events': {
      id: '/about/news-events'
      path: '/news-events'
      fullPath: '/about/news-events'
      preLoaderRoute: typeof AboutNewsEventsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/notices': {
      id: '/about/notices'
      path: '/notices'
      fullPath: '/about/notices'
      preLoaderRoute: typeof AboutNoticesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-story': {
      id: '/about/our-story'
      path: '/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/signature-school': {
      id: '/about/signature-school'
      path: '/signature-school'
      fullPath: '/about/signature-school'
      preLoaderRoute: typeof AboutSignatureSchoolRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/teacher-training': {
      id: '/about/teacher-training'
      path: '/teacher-training'
      fullPath: '/about/teacher-training'
      preLoaderRoute: typeof AboutTeacherTrainingRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/api/send-digest': {
      id: '/api/send-digest'
      path: '/api/send-digest'
      fullPath: '/api/send-digest'
      preLoaderRoute: typeof ApiSendDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/apply': {
      id: '/careers/apply'
      path: '/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cms': {
      id: '/dashboard/cms'
      path: '/cms'
      fullPath: '/dashboard/cms'
      preLoaderRoute: typeof DashboardCmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forgot-password': {
      id: '/dashboard/forgot-password'
      path: '/forgot-password'
      fullPath: '/dashboard/forgot-password'
      preLoaderRoute: typeof DashboardForgotPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instructor': {
      id: '/dashboard/instructor'
      path: '/instructor'
      fullPath: '/dashboard/instructor'
      preLoaderRoute: typeof DashboardInstructorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reset-password': {
      id: '/dashboard/reset-password'
      path: '/reset-password'
      fullPath: '/dashboard/reset-password'
      preLoaderRoute: typeof DashboardResetPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/school': {
      id: '/dashboard/school'
      path: '/school'
      fullPath: '/dashboard/school'
      preLoaderRoute: typeof DashboardSchoolRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signup': {
      id: '/dashboard/signup'
      path: '/signup'
      fullPath: '/dashboard/signup'
      preLoaderRoute: typeof DashboardSignupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/digital-school/parent-portal': {
      id: '/digital-school/parent-portal'
      path: '/digital-school/parent-portal'
      fullPath: '/digital-school/parent-portal'
      preLoaderRoute: typeof DigitalSchoolParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-school/student-portal': {
      id: '/digital-school/student-portal'
      path: '/digital-school/student-portal'
      fullPath: '/digital-school/student-portal'
      preLoaderRoute: typeof DigitalSchoolStudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-school/teacher-portal': {
      id: '/digital-school/teacher-portal'
      path: '/digital-school/teacher-portal'
      fullPath: '/digital-school/teacher-portal'
      preLoaderRoute: typeof DigitalSchoolTeacherPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise/apply': {
      id: '/franchise/apply'
      path: '/apply'
      fullPath: '/franchise/apply'
      preLoaderRoute: typeof FranchiseApplyRouteImport
      parentRoute: typeof FranchiseRoute
    }
    '/news-events/': {
      id: '/news-events/'
      path: '/'
      fullPath: '/news-events/'
      preLoaderRoute: typeof NewsEventsIndexRouteImport
      parentRoute: typeof NewsEventsRoute
    }
    '/news-events/$slug': {
      id: '/news-events/$slug'
      path: '/$slug'
      fullPath: '/news-events/$slug'
      preLoaderRoute: typeof NewsEventsSlugRouteImport
      parentRoute: typeof NewsEventsRoute
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/tickets': {
      id: '/support/tickets'
      path: '/tickets'
      fullPath: '/support/tickets'
      preLoaderRoute: typeof SupportTicketsRouteImport
      parentRoute: typeof SupportRoute
    }
    '/about/notices/': {
      id: '/about/notices/'
      path: '/'
      fullPath: '/about/notices/'
      preLoaderRoute: typeof AboutNoticesIndexRouteImport
      parentRoute: typeof AboutNoticesRoute
    }
    '/about/notices/$noticeId': {
      id: '/about/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/about/notices/$noticeId'
      preLoaderRoute: typeof AboutNoticesNoticeIdRouteImport
      parentRoute: typeof AboutNoticesRoute
    }
    '/academics/calendar/$id': {
      id: '/academics/calendar/$id'
      path: '/calendar/$id'
      fullPath: '/academics/calendar/$id'
      preLoaderRoute: typeof AcademicsCalendarIdRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/audit-log': {
      id: '/dashboard/admin/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/admin/audit-log'
      preLoaderRoute: typeof DashboardAdminAuditLogRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/overview': {
      id: '/dashboard/admin/overview'
      path: '/overview'
      fullPath: '/dashboard/admin/overview'
      preLoaderRoute: typeof DashboardAdminOverviewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/promotion': {
      id: '/dashboard/admin/promotion'
      path: '/promotion'
      fullPath: '/dashboard/admin/promotion'
      preLoaderRoute: typeof DashboardAdminPromotionRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/sessions': {
      id: '/dashboard/admin/sessions'
      path: '/sessions'
      fullPath: '/dashboard/admin/sessions'
      preLoaderRoute: typeof DashboardAdminSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/site': {
      id: '/dashboard/admin/site'
      path: '/site'
      fullPath: '/dashboard/admin/site'
      preLoaderRoute: typeof DashboardAdminSiteRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/submissions': {
      id: '/dashboard/admin/submissions'
      path: '/submissions'
      fullPath: '/dashboard/admin/submissions'
      preLoaderRoute: typeof DashboardAdminSubmissionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/terms': {
      id: '/dashboard/admin/terms'
      path: '/terms'
      fullPath: '/dashboard/admin/terms'
      preLoaderRoute: typeof DashboardAdminTermsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/whitelist': {
      id: '/dashboard/admin/whitelist'
      path: '/whitelist'
      fullPath: '/dashboard/admin/whitelist'
      preLoaderRoute: typeof DashboardAdminWhitelistRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/cms/': {
      id: '/dashboard/cms/'
      path: '/'
      fullPath: '/dashboard/cms/'
      preLoaderRoute: typeof DashboardCmsIndexRouteImport
      parentRoute: typeof DashboardCmsRoute
    }
    '/dashboard/instructor/': {
      id: '/dashboard/instructor/'
      path: '/'
      fullPath: '/dashboard/instructor/'
      preLoaderRoute: typeof DashboardInstructorIndexRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/school/': {
      id: '/dashboard/school/'
      path: '/'
      fullPath: '/dashboard/school/'
      preLoaderRoute: typeof DashboardSchoolIndexRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/invoices': {
      id: '/dashboard/school/invoices'
      path: '/invoices'
      fullPath: '/dashboard/school/invoices'
      preLoaderRoute: typeof DashboardSchoolInvoicesRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/summary': {
      id: '/dashboard/school/summary'
      path: '/summary'
      fullPath: '/dashboard/school/summary'
      preLoaderRoute: typeof DashboardSchoolSummaryRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/admin/instructors/': {
      id: '/dashboard/admin/instructors/'
      path: '/instructors'
      fullPath: '/dashboard/admin/instructors/'
      preLoaderRoute: typeof DashboardAdminInstructorsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/instructors/$instructorEmail': {
      id: '/dashboard/admin/instructors/$instructorEmail'
      path: '/instructors/$instructorEmail'
      fullPath: '/dashboard/admin/instructors/$instructorEmail'
      preLoaderRoute: typeof DashboardAdminInstructorsInstructorEmailRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/invoices/': {
      id: '/dashboard/admin/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/admin/invoices/'
      preLoaderRoute: typeof DashboardAdminInvoicesIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/invoices/$invoiceId': {
      id: '/dashboard/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/admin/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/schools/': {
      id: '/dashboard/admin/schools/'
      path: '/schools'
      fullPath: '/dashboard/admin/schools/'
      preLoaderRoute: typeof DashboardAdminSchoolsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/student/$studentId': {
      id: '/dashboard/admin/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/admin/student/$studentId'
      preLoaderRoute: typeof DashboardAdminStudentStudentIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/instructor/section/$sectionId': {
      id: '/dashboard/instructor/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/dashboard/instructor/section/$sectionId'
      preLoaderRoute: typeof DashboardInstructorSectionSectionIdRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/instructor/student/$studentId': {
      id: '/dashboard/instructor/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/instructor/student/$studentId'
      preLoaderRoute: typeof DashboardInstructorStudentStudentIdRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/school/section/$sectionId': {
      id: '/dashboard/school/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/dashboard/school/section/$sectionId'
      preLoaderRoute: typeof DashboardSchoolSectionSectionIdRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/student/$studentId': {
      id: '/dashboard/school/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/school/student/$studentId'
      preLoaderRoute: typeof DashboardSchoolStudentStudentIdRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/admin/schools/$schoolId/sections/': {
      id: '/dashboard/admin/schools/$schoolId/sections/'
      path: '/schools/$schoolId/sections'
      fullPath: '/dashboard/admin/schools/$schoolId/sections/'
      preLoaderRoute: typeof DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': {
      id: '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
      path: '/schools/$schoolId/sections/$sectionId/sessions'
      fullPath: '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
      preLoaderRoute: typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface AboutNoticesRouteChildren {
  AboutNoticesNoticeIdRoute: typeof AboutNoticesNoticeIdRoute
  AboutNoticesIndexRoute: typeof AboutNoticesIndexRoute
}

const AboutNoticesRouteChildren: AboutNoticesRouteChildren = {
  AboutNoticesNoticeIdRoute: AboutNoticesNoticeIdRoute,
  AboutNoticesIndexRoute: AboutNoticesIndexRoute,
}

const AboutNoticesRouteWithChildren = AboutNoticesRoute._addFileChildren(
  AboutNoticesRouteChildren,
)

interface AboutRouteChildren {
  AboutAlumniRoute: typeof AboutAlumniRoute
  AboutAtAGlanceRoute: typeof AboutAtAGlanceRoute
  AboutChairpersonRoute: typeof AboutChairpersonRoute
  AboutEducationalPhilosophyRoute: typeof AboutEducationalPhilosophyRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutNewsEventsRoute: typeof AboutNewsEventsRoute
  AboutNoticesRoute: typeof AboutNoticesRouteWithChildren
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutSignatureSchoolRoute: typeof AboutSignatureSchoolRoute
  AboutTeacherTrainingRoute: typeof AboutTeacherTrainingRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAlumniRoute: AboutAlumniRoute,
  AboutAtAGlanceRoute: AboutAtAGlanceRoute,
  AboutChairpersonRoute: AboutChairpersonRoute,
  AboutEducationalPhilosophyRoute: AboutEducationalPhilosophyRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutNewsEventsRoute: AboutNewsEventsRoute,
  AboutNoticesRoute: AboutNoticesRouteWithChildren,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutSignatureSchoolRoute: AboutSignatureSchoolRoute,
  AboutTeacherTrainingRoute: AboutTeacherTrainingRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AcademicsRouteChildren {
  AcademicsCalendarIdRoute: typeof AcademicsCalendarIdRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsCalendarIdRoute: AcademicsCalendarIdRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

interface CareersRouteChildren {
  CareersApplyRoute: typeof CareersApplyRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersApplyRoute: CareersApplyRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminAuditLogRoute: typeof DashboardAdminAuditLogRoute
  DashboardAdminOverviewRoute: typeof DashboardAdminOverviewRoute
  DashboardAdminPromotionRoute: typeof DashboardAdminPromotionRoute
  DashboardAdminSessionsRoute: typeof DashboardAdminSessionsRoute
  DashboardAdminSiteRoute: typeof DashboardAdminSiteRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminSubmissionsRoute: typeof DashboardAdminSubmissionsRoute
  DashboardAdminTermsRoute: typeof DashboardAdminTermsRoute
  DashboardAdminWhitelistRoute: typeof DashboardAdminWhitelistRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminInstructorsInstructorEmailRoute: typeof DashboardAdminInstructorsInstructorEmailRoute
  DashboardAdminInvoicesInvoiceIdRoute: typeof DashboardAdminInvoicesInvoiceIdRoute
  DashboardAdminStudentStudentIdRoute: typeof DashboardAdminStudentStudentIdRoute
  DashboardAdminInstructorsIndexRoute: typeof DashboardAdminInstructorsIndexRoute
  DashboardAdminInvoicesIndexRoute: typeof DashboardAdminInvoicesIndexRoute
  DashboardAdminSchoolsIndexRoute: typeof DashboardAdminSchoolsIndexRoute
  DashboardAdminSchoolsSchoolIdSectionsIndexRoute: typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute: typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAuditLogRoute: DashboardAdminAuditLogRoute,
  DashboardAdminOverviewRoute: DashboardAdminOverviewRoute,
  DashboardAdminPromotionRoute: DashboardAdminPromotionRoute,
  DashboardAdminSessionsRoute: DashboardAdminSessionsRoute,
  DashboardAdminSiteRoute: DashboardAdminSiteRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminSubmissionsRoute: DashboardAdminSubmissionsRoute,
  DashboardAdminTermsRoute: DashboardAdminTermsRoute,
  DashboardAdminWhitelistRoute: DashboardAdminWhitelistRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminInstructorsInstructorEmailRoute:
    DashboardAdminInstructorsInstructorEmailRoute,
  DashboardAdminInvoicesInvoiceIdRoute: DashboardAdminInvoicesInvoiceIdRoute,
  DashboardAdminStudentStudentIdRoute: DashboardAdminStudentStudentIdRoute,
  DashboardAdminInstructorsIndexRoute: DashboardAdminInstructorsIndexRoute,
  DashboardAdminInvoicesIndexRoute: DashboardAdminInvoicesIndexRoute,
  DashboardAdminSchoolsIndexRoute: DashboardAdminSchoolsIndexRoute,
  DashboardAdminSchoolsSchoolIdSectionsIndexRoute:
    DashboardAdminSchoolsSchoolIdSectionsIndexRoute,
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute:
    DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardCmsRouteChildren {
  DashboardCmsIndexRoute: typeof DashboardCmsIndexRoute
}

const DashboardCmsRouteChildren: DashboardCmsRouteChildren = {
  DashboardCmsIndexRoute: DashboardCmsIndexRoute,
}

const DashboardCmsRouteWithChildren = DashboardCmsRoute._addFileChildren(
  DashboardCmsRouteChildren,
)

interface DashboardInstructorRouteChildren {
  DashboardInstructorIndexRoute: typeof DashboardInstructorIndexRoute
  DashboardInstructorSectionSectionIdRoute: typeof DashboardInstructorSectionSectionIdRoute
  DashboardInstructorStudentStudentIdRoute: typeof DashboardInstructorStudentStudentIdRoute
}

const DashboardInstructorRouteChildren: DashboardInstructorRouteChildren = {
  DashboardInstructorIndexRoute: DashboardInstructorIndexRoute,
  DashboardInstructorSectionSectionIdRoute:
    DashboardInstructorSectionSectionIdRoute,
  DashboardInstructorStudentStudentIdRoute:
    DashboardInstructorStudentStudentIdRoute,
}

const DashboardInstructorRouteWithChildren =
  DashboardInstructorRoute._addFileChildren(DashboardInstructorRouteChildren)

interface DashboardSchoolRouteChildren {
  DashboardSchoolInvoicesRoute: typeof DashboardSchoolInvoicesRoute
  DashboardSchoolSummaryRoute: typeof DashboardSchoolSummaryRoute
  DashboardSchoolIndexRoute: typeof DashboardSchoolIndexRoute
  DashboardSchoolSectionSectionIdRoute: typeof DashboardSchoolSectionSectionIdRoute
  DashboardSchoolStudentStudentIdRoute: typeof DashboardSchoolStudentStudentIdRoute
}

const DashboardSchoolRouteChildren: DashboardSchoolRouteChildren = {
  DashboardSchoolInvoicesRoute: DashboardSchoolInvoicesRoute,
  DashboardSchoolSummaryRoute: DashboardSchoolSummaryRoute,
  DashboardSchoolIndexRoute: DashboardSchoolIndexRoute,
  DashboardSchoolSectionSectionIdRoute: DashboardSchoolSectionSectionIdRoute,
  DashboardSchoolStudentStudentIdRoute: DashboardSchoolStudentStudentIdRoute,
}

const DashboardSchoolRouteWithChildren = DashboardSchoolRoute._addFileChildren(
  DashboardSchoolRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardCmsRoute: typeof DashboardCmsRouteWithChildren
  DashboardForgotPasswordRoute: typeof DashboardForgotPasswordRoute
  DashboardInstructorRoute: typeof DashboardInstructorRouteWithChildren
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardResetPasswordRoute: typeof DashboardResetPasswordRoute
  DashboardSchoolRoute: typeof DashboardSchoolRouteWithChildren
  DashboardSignupRoute: typeof DashboardSignupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardCmsRoute: DashboardCmsRouteWithChildren,
  DashboardForgotPasswordRoute: DashboardForgotPasswordRoute,
  DashboardInstructorRoute: DashboardInstructorRouteWithChildren,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardResetPasswordRoute: DashboardResetPasswordRoute,
  DashboardSchoolRoute: DashboardSchoolRouteWithChildren,
  DashboardSignupRoute: DashboardSignupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FranchiseRouteChildren {
  FranchiseApplyRoute: typeof FranchiseApplyRoute
}

const FranchiseRouteChildren: FranchiseRouteChildren = {
  FranchiseApplyRoute: FranchiseApplyRoute,
}

const FranchiseRouteWithChildren = FranchiseRoute._addFileChildren(
  FranchiseRouteChildren,
)

interface NewsEventsRouteChildren {
  NewsEventsSlugRoute: typeof NewsEventsSlugRoute
  NewsEventsIndexRoute: typeof NewsEventsIndexRoute
}

const NewsEventsRouteChildren: NewsEventsRouteChildren = {
  NewsEventsSlugRoute: NewsEventsSlugRoute,
  NewsEventsIndexRoute: NewsEventsIndexRoute,
}

const NewsEventsRouteWithChildren = NewsEventsRoute._addFileChildren(
  NewsEventsRouteChildren,
)

interface SupportRouteChildren {
  SupportTicketsRoute: typeof SupportTicketsRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketsRoute: SupportTicketsRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AcademicsRoute: AcademicsRouteWithChildren,
  AdmissionProcedureRoute: AdmissionProcedureRoute,
  AdmissionsRoute: AdmissionsRoute,
  ApplyOnlineRoute: ApplyOnlineRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DigitalLearningRoute: DigitalLearningRoute,
  EmailPreviewRoute: EmailPreviewRoute,
  ExaminationsRoute: ExaminationsRoute,
  FaqsRoute: FaqsRoute,
  FindACampusRoute: FindACampusRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  FranchiseRoute: FranchiseRouteWithChildren,
  FutureSkillsRoute: FutureSkillsRoute,
  LeadershipRoute: LeadershipRoute,
  LearnToEarnRoute: LearnToEarnRoute,
  LoginRoute: LoginRoute,
  NewsEventsRoute: NewsEventsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ProjectsRoute: ProjectsRoute,
  SchoolRoute: SchoolRoute,
  SchoolsRoute: SchoolsRoute,
  SteamRoute: SteamRoute,
  StudentLifeRoute: StudentLifeRoute,
  StudentWellbeingRoute: StudentWellbeingRoute,
  StudentsRoute: StudentsRoute,
  SupportRoute: SupportRouteWithChildren,
  TeacherDevelopmentRoute: TeacherDevelopmentRoute,
  ApiSendDigestRoute: ApiSendDigestRoute,
  DigitalSchoolParentPortalRoute: DigitalSchoolParentPortalRoute,
  DigitalSchoolStudentPortalRoute: DigitalSchoolStudentPortalRoute,
  DigitalSchoolTeacherPortalRoute: DigitalSchoolTeacherPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
