/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ApiSendDigestRouteImport } from './routes/api/send-digest'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardCmsRouteImport } from './routes/dashboard.cms'
import { Route as DashboardForgotPasswordRouteImport } from './routes/dashboard.forgot-password'
import { Route as DashboardInstructorRouteImport } from './routes/dashboard.instructor'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardResetPasswordRouteImport } from './routes/dashboard.reset-password'
import { Route as DashboardSchoolRouteImport } from './routes/dashboard.school'
import { Route as DashboardSignupRouteImport } from './routes/dashboard.signup'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminAuditLogRouteImport } from './routes/dashboard.admin.audit-log'
import { Route as DashboardAdminOverviewRouteImport } from './routes/dashboard.admin.overview'
import { Route as DashboardAdminPromotionRouteImport } from './routes/dashboard.admin.promotion'
import { Route as DashboardAdminSessionsRouteImport } from './routes/dashboard.admin.sessions'
import { Route as DashboardAdminSiteRouteImport } from './routes/dashboard.admin.site'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminSubmissionsRouteImport } from './routes/dashboard.admin.submissions'
import { Route as DashboardAdminTermsRouteImport } from './routes/dashboard.admin.terms'
import { Route as DashboardAdminWhitelistRouteImport } from './routes/dashboard.admin.whitelist'
import { Route as DashboardCmsIndexRouteImport } from './routes/dashboard.cms.index'
import { Route as DashboardInstructorIndexRouteImport } from './routes/dashboard.instructor.index'
import { Route as DashboardSchoolIndexRouteImport } from './routes/dashboard.school.index'
import { Route as DashboardSchoolInvoicesRouteImport } from './routes/dashboard.school.invoices'
import { Route as DashboardSchoolSummaryRouteImport } from './routes/dashboard.school.summary'
import { Route as DashboardAdminInstructorsIndexRouteImport } from './routes/dashboard.admin.instructors.index'
import { Route as DashboardAdminInstructorsInstructorEmailRouteImport } from './routes/dashboard.admin.instructors.$instructorEmail'
import { Route as DashboardAdminInvoicesIndexRouteImport } from './routes/dashboard.admin.invoices.index'
import { Route as DashboardAdminInvoicesInvoiceIdRouteImport } from './routes/dashboard.admin.invoices.$invoiceId'
import { Route as DashboardAdminSchoolsIndexRouteImport } from './routes/dashboard.admin.schools.index'
import { Route as DashboardAdminStudentStudentIdRouteImport } from './routes/dashboard.admin.student.$studentId'
import { Route as DashboardInstructorSectionSectionIdRouteImport } from './routes/dashboard.instructor.section.$sectionId'
import { Route as DashboardInstructorStudentStudentIdRouteImport } from './routes/dashboard.instructor.student.$studentId'
import { Route as DashboardSchoolSectionSectionIdRouteImport } from './routes/dashboard.school.section.$sectionId'
import { Route as DashboardSchoolStudentStudentIdRouteImport } from './routes/dashboard.school.student.$studentId'
import { Route as DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport } from './routes/dashboard.admin.schools.$schoolId.sections.index'
import { Route as DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport } from './routes/dashboard.admin.schools.$schoolId.sections.$sectionId.sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendDigestRoute = ApiSendDigestRouteImport.update({
  id: '/api/send-digest',
  path: '/api/send-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCmsRoute = DashboardCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForgotPasswordRoute = DashboardForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstructorRoute = DashboardInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResetPasswordRoute = DashboardResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchoolRoute = DashboardSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignupRoute = DashboardSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAuditLogRoute = DashboardAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminOverviewRoute = DashboardAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPromotionRoute = DashboardAdminPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSessionsRoute = DashboardAdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSiteRoute = DashboardAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSubmissionsRoute =
  DashboardAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminTermsRoute = DashboardAdminTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminWhitelistRoute = DashboardAdminWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardCmsIndexRoute = DashboardCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCmsRoute,
} as any)
const DashboardInstructorIndexRoute =
  DashboardInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardSchoolIndexRoute = DashboardSchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardSchoolInvoicesRoute = DashboardSchoolInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardSchoolSummaryRoute = DashboardSchoolSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DashboardSchoolRoute,
} as any)
const DashboardAdminInstructorsIndexRoute =
  DashboardAdminInstructorsIndexRouteImport.update({
    id: '/instructors/',
    path: '/instructors/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInstructorsInstructorEmailRoute =
  DashboardAdminInstructorsInstructorEmailRouteImport.update({
    id: '/instructors/$instructorEmail',
    path: '/instructors/$instructorEmail',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInvoicesIndexRoute =
  DashboardAdminInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInvoicesInvoiceIdRoute =
  DashboardAdminInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSchoolsIndexRoute =
  DashboardAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminStudentStudentIdRoute =
  DashboardAdminStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardInstructorSectionSectionIdRoute =
  DashboardInstructorSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardInstructorStudentStudentIdRoute =
  DashboardInstructorStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardInstructorRoute,
  } as any)
const DashboardSchoolSectionSectionIdRoute =
  DashboardSchoolSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => DashboardSchoolRoute,
  } as any)
const DashboardSchoolStudentStudentIdRoute =
  DashboardSchoolStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => DashboardSchoolRoute,
  } as any)
const DashboardAdminSchoolsSchoolIdSectionsIndexRoute =
  DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport.update({
    id: '/schools/$schoolId/sections/',
    path: '/schools/$schoolId/sections/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute =
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport.update({
    id: '/schools/$schoolId/sections/$sectionId/sessions',
    path: '/schools/$schoolId/sections/$sectionId/sessions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/email-preview': typeof EmailPreviewRoute
  '/for-schools': typeof ForSchoolsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/schools': typeof SchoolsRoute
  '/students': typeof StudentsRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteWithChildren
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/instructor': typeof DashboardInstructorRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/school': typeof DashboardSchoolRouteWithChildren
  '/dashboard/signup': typeof DashboardSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/instructor/': typeof DashboardInstructorIndexRoute
  '/dashboard/school/': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors/': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices/': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools/': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/email-preview': typeof EmailPreviewRoute
  '/for-schools': typeof ForSchoolsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/schools': typeof SchoolsRoute
  '/students': typeof StudentsRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/cms': typeof DashboardCmsIndexRoute
  '/dashboard/instructor': typeof DashboardInstructorIndexRoute
  '/dashboard/school': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/email-preview': typeof EmailPreviewRoute
  '/for-schools': typeof ForSchoolsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/schools': typeof SchoolsRoute
  '/students': typeof StudentsRoute
  '/api/send-digest': typeof ApiSendDigestRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/cms': typeof DashboardCmsRouteWithChildren
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/instructor': typeof DashboardInstructorRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/school': typeof DashboardSchoolRouteWithChildren
  '/dashboard/signup': typeof DashboardSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/audit-log': typeof DashboardAdminAuditLogRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/promotion': typeof DashboardAdminPromotionRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/site': typeof DashboardAdminSiteRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/submissions': typeof DashboardAdminSubmissionsRoute
  '/dashboard/admin/terms': typeof DashboardAdminTermsRoute
  '/dashboard/admin/whitelist': typeof DashboardAdminWhitelistRoute
  '/dashboard/school/invoices': typeof DashboardSchoolInvoicesRoute
  '/dashboard/school/summary': typeof DashboardSchoolSummaryRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/cms/': typeof DashboardCmsIndexRoute
  '/dashboard/instructor/': typeof DashboardInstructorIndexRoute
  '/dashboard/school/': typeof DashboardSchoolIndexRoute
  '/dashboard/admin/instructors/$instructorEmail': typeof DashboardAdminInstructorsInstructorEmailRoute
  '/dashboard/admin/invoices/$invoiceId': typeof DashboardAdminInvoicesInvoiceIdRoute
  '/dashboard/admin/student/$studentId': typeof DashboardAdminStudentStudentIdRoute
  '/dashboard/instructor/section/$sectionId': typeof DashboardInstructorSectionSectionIdRoute
  '/dashboard/instructor/student/$studentId': typeof DashboardInstructorStudentStudentIdRoute
  '/dashboard/school/section/$sectionId': typeof DashboardSchoolSectionSectionIdRoute
  '/dashboard/school/student/$studentId': typeof DashboardSchoolStudentStudentIdRoute
  '/dashboard/admin/instructors/': typeof DashboardAdminInstructorsIndexRoute
  '/dashboard/admin/invoices/': typeof DashboardAdminInvoicesIndexRoute
  '/dashboard/admin/schools/': typeof DashboardAdminSchoolsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/': typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/email-preview'
    | '/for-schools'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/schools'
    | '/students'
    | '/api/send-digest'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/forgot-password'
    | '/dashboard/instructor'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/school'
    | '/dashboard/signup'
    | '/dashboard/'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/dashboard/admin/'
    | '/dashboard/cms/'
    | '/dashboard/instructor/'
    | '/dashboard/school/'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors/'
    | '/dashboard/admin/invoices/'
    | '/dashboard/admin/schools/'
    | '/dashboard/admin/schools/$schoolId/sections/'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/careers'
    | '/contact'
    | '/email-preview'
    | '/for-schools'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/schools'
    | '/students'
    | '/api/send-digest'
    | '/dashboard/account'
    | '/dashboard/forgot-password'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/signup'
    | '/dashboard'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/instructor'
    | '/dashboard/school'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors'
    | '/dashboard/admin/invoices'
    | '/dashboard/admin/schools'
    | '/dashboard/admin/schools/$schoolId/sections'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/email-preview'
    | '/for-schools'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/projects'
    | '/schools'
    | '/students'
    | '/api/send-digest'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/cms'
    | '/dashboard/forgot-password'
    | '/dashboard/instructor'
    | '/dashboard/login'
    | '/dashboard/reset-password'
    | '/dashboard/school'
    | '/dashboard/signup'
    | '/dashboard/'
    | '/dashboard/admin/audit-log'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/promotion'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/site'
    | '/dashboard/admin/students'
    | '/dashboard/admin/submissions'
    | '/dashboard/admin/terms'
    | '/dashboard/admin/whitelist'
    | '/dashboard/school/invoices'
    | '/dashboard/school/summary'
    | '/dashboard/admin/'
    | '/dashboard/cms/'
    | '/dashboard/instructor/'
    | '/dashboard/school/'
    | '/dashboard/admin/instructors/$instructorEmail'
    | '/dashboard/admin/invoices/$invoiceId'
    | '/dashboard/admin/student/$studentId'
    | '/dashboard/instructor/section/$sectionId'
    | '/dashboard/instructor/student/$studentId'
    | '/dashboard/school/section/$sectionId'
    | '/dashboard/school/student/$studentId'
    | '/dashboard/admin/instructors/'
    | '/dashboard/admin/invoices/'
    | '/dashboard/admin/schools/'
    | '/dashboard/admin/schools/$schoolId/sections/'
    | '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmailPreviewRoute: typeof EmailPreviewRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ProjectsRoute: typeof ProjectsRoute
  SchoolsRoute: typeof SchoolsRoute
  StudentsRoute: typeof StudentsRoute
  ApiSendDigestRoute: typeof ApiSendDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-digest': {
      id: '/api/send-digest'
      path: '/api/send-digest'
      fullPath: '/api/send-digest'
      preLoaderRoute: typeof ApiSendDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cms': {
      id: '/dashboard/cms'
      path: '/cms'
      fullPath: '/dashboard/cms'
      preLoaderRoute: typeof DashboardCmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forgot-password': {
      id: '/dashboard/forgot-password'
      path: '/forgot-password'
      fullPath: '/dashboard/forgot-password'
      preLoaderRoute: typeof DashboardForgotPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instructor': {
      id: '/dashboard/instructor'
      path: '/instructor'
      fullPath: '/dashboard/instructor'
      preLoaderRoute: typeof DashboardInstructorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reset-password': {
      id: '/dashboard/reset-password'
      path: '/reset-password'
      fullPath: '/dashboard/reset-password'
      preLoaderRoute: typeof DashboardResetPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/school': {
      id: '/dashboard/school'
      path: '/school'
      fullPath: '/dashboard/school'
      preLoaderRoute: typeof DashboardSchoolRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signup': {
      id: '/dashboard/signup'
      path: '/signup'
      fullPath: '/dashboard/signup'
      preLoaderRoute: typeof DashboardSignupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/audit-log': {
      id: '/dashboard/admin/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/admin/audit-log'
      preLoaderRoute: typeof DashboardAdminAuditLogRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/overview': {
      id: '/dashboard/admin/overview'
      path: '/overview'
      fullPath: '/dashboard/admin/overview'
      preLoaderRoute: typeof DashboardAdminOverviewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/promotion': {
      id: '/dashboard/admin/promotion'
      path: '/promotion'
      fullPath: '/dashboard/admin/promotion'
      preLoaderRoute: typeof DashboardAdminPromotionRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/sessions': {
      id: '/dashboard/admin/sessions'
      path: '/sessions'
      fullPath: '/dashboard/admin/sessions'
      preLoaderRoute: typeof DashboardAdminSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/site': {
      id: '/dashboard/admin/site'
      path: '/site'
      fullPath: '/dashboard/admin/site'
      preLoaderRoute: typeof DashboardAdminSiteRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/submissions': {
      id: '/dashboard/admin/submissions'
      path: '/submissions'
      fullPath: '/dashboard/admin/submissions'
      preLoaderRoute: typeof DashboardAdminSubmissionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/terms': {
      id: '/dashboard/admin/terms'
      path: '/terms'
      fullPath: '/dashboard/admin/terms'
      preLoaderRoute: typeof DashboardAdminTermsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/whitelist': {
      id: '/dashboard/admin/whitelist'
      path: '/whitelist'
      fullPath: '/dashboard/admin/whitelist'
      preLoaderRoute: typeof DashboardAdminWhitelistRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/cms/': {
      id: '/dashboard/cms/'
      path: '/'
      fullPath: '/dashboard/cms/'
      preLoaderRoute: typeof DashboardCmsIndexRouteImport
      parentRoute: typeof DashboardCmsRoute
    }
    '/dashboard/instructor/': {
      id: '/dashboard/instructor/'
      path: '/'
      fullPath: '/dashboard/instructor/'
      preLoaderRoute: typeof DashboardInstructorIndexRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/school/': {
      id: '/dashboard/school/'
      path: '/'
      fullPath: '/dashboard/school/'
      preLoaderRoute: typeof DashboardSchoolIndexRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/invoices': {
      id: '/dashboard/school/invoices'
      path: '/invoices'
      fullPath: '/dashboard/school/invoices'
      preLoaderRoute: typeof DashboardSchoolInvoicesRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/summary': {
      id: '/dashboard/school/summary'
      path: '/summary'
      fullPath: '/dashboard/school/summary'
      preLoaderRoute: typeof DashboardSchoolSummaryRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/admin/instructors/': {
      id: '/dashboard/admin/instructors/'
      path: '/instructors'
      fullPath: '/dashboard/admin/instructors/'
      preLoaderRoute: typeof DashboardAdminInstructorsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/instructors/$instructorEmail': {
      id: '/dashboard/admin/instructors/$instructorEmail'
      path: '/instructors/$instructorEmail'
      fullPath: '/dashboard/admin/instructors/$instructorEmail'
      preLoaderRoute: typeof DashboardAdminInstructorsInstructorEmailRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/invoices/': {
      id: '/dashboard/admin/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/admin/invoices/'
      preLoaderRoute: typeof DashboardAdminInvoicesIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/invoices/$invoiceId': {
      id: '/dashboard/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/admin/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/schools/': {
      id: '/dashboard/admin/schools/'
      path: '/schools'
      fullPath: '/dashboard/admin/schools/'
      preLoaderRoute: typeof DashboardAdminSchoolsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/student/$studentId': {
      id: '/dashboard/admin/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/admin/student/$studentId'
      preLoaderRoute: typeof DashboardAdminStudentStudentIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/instructor/section/$sectionId': {
      id: '/dashboard/instructor/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/dashboard/instructor/section/$sectionId'
      preLoaderRoute: typeof DashboardInstructorSectionSectionIdRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/instructor/student/$studentId': {
      id: '/dashboard/instructor/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/instructor/student/$studentId'
      preLoaderRoute: typeof DashboardInstructorStudentStudentIdRouteImport
      parentRoute: typeof DashboardInstructorRoute
    }
    '/dashboard/school/section/$sectionId': {
      id: '/dashboard/school/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/dashboard/school/section/$sectionId'
      preLoaderRoute: typeof DashboardSchoolSectionSectionIdRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/school/student/$studentId': {
      id: '/dashboard/school/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/dashboard/school/student/$studentId'
      preLoaderRoute: typeof DashboardSchoolStudentStudentIdRouteImport
      parentRoute: typeof DashboardSchoolRoute
    }
    '/dashboard/admin/schools/$schoolId/sections/': {
      id: '/dashboard/admin/schools/$schoolId/sections/'
      path: '/schools/$schoolId/sections'
      fullPath: '/dashboard/admin/schools/$schoolId/sections/'
      preLoaderRoute: typeof DashboardAdminSchoolsSchoolIdSectionsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions': {
      id: '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
      path: '/schools/$schoolId/sections/$sectionId/sessions'
      fullPath: '/dashboard/admin/schools/$schoolId/sections/$sectionId/sessions'
      preLoaderRoute: typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAuditLogRoute: typeof DashboardAdminAuditLogRoute
  DashboardAdminOverviewRoute: typeof DashboardAdminOverviewRoute
  DashboardAdminPromotionRoute: typeof DashboardAdminPromotionRoute
  DashboardAdminSessionsRoute: typeof DashboardAdminSessionsRoute
  DashboardAdminSiteRoute: typeof DashboardAdminSiteRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminSubmissionsRoute: typeof DashboardAdminSubmissionsRoute
  DashboardAdminTermsRoute: typeof DashboardAdminTermsRoute
  DashboardAdminWhitelistRoute: typeof DashboardAdminWhitelistRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminInstructorsInstructorEmailRoute: typeof DashboardAdminInstructorsInstructorEmailRoute
  DashboardAdminInvoicesInvoiceIdRoute: typeof DashboardAdminInvoicesInvoiceIdRoute
  DashboardAdminStudentStudentIdRoute: typeof DashboardAdminStudentStudentIdRoute
  DashboardAdminInstructorsIndexRoute: typeof DashboardAdminInstructorsIndexRoute
  DashboardAdminInvoicesIndexRoute: typeof DashboardAdminInvoicesIndexRoute
  DashboardAdminSchoolsIndexRoute: typeof DashboardAdminSchoolsIndexRoute
  DashboardAdminSchoolsSchoolIdSectionsIndexRoute: typeof DashboardAdminSchoolsSchoolIdSectionsIndexRoute
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute: typeof DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAuditLogRoute: DashboardAdminAuditLogRoute,
  DashboardAdminOverviewRoute: DashboardAdminOverviewRoute,
  DashboardAdminPromotionRoute: DashboardAdminPromotionRoute,
  DashboardAdminSessionsRoute: DashboardAdminSessionsRoute,
  DashboardAdminSiteRoute: DashboardAdminSiteRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminSubmissionsRoute: DashboardAdminSubmissionsRoute,
  DashboardAdminTermsRoute: DashboardAdminTermsRoute,
  DashboardAdminWhitelistRoute: DashboardAdminWhitelistRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminInstructorsInstructorEmailRoute:
    DashboardAdminInstructorsInstructorEmailRoute,
  DashboardAdminInvoicesInvoiceIdRoute: DashboardAdminInvoicesInvoiceIdRoute,
  DashboardAdminStudentStudentIdRoute: DashboardAdminStudentStudentIdRoute,
  DashboardAdminInstructorsIndexRoute: DashboardAdminInstructorsIndexRoute,
  DashboardAdminInvoicesIndexRoute: DashboardAdminInvoicesIndexRoute,
  DashboardAdminSchoolsIndexRoute: DashboardAdminSchoolsIndexRoute,
  DashboardAdminSchoolsSchoolIdSectionsIndexRoute:
    DashboardAdminSchoolsSchoolIdSectionsIndexRoute,
  DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute:
    DashboardAdminSchoolsSchoolIdSectionsSectionIdSessionsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardCmsRouteChildren {
  DashboardCmsIndexRoute: typeof DashboardCmsIndexRoute
}

const DashboardCmsRouteChildren: DashboardCmsRouteChildren = {
  DashboardCmsIndexRoute: DashboardCmsIndexRoute,
}

const DashboardCmsRouteWithChildren = DashboardCmsRoute._addFileChildren(
  DashboardCmsRouteChildren,
)

interface DashboardInstructorRouteChildren {
  DashboardInstructorIndexRoute: typeof DashboardInstructorIndexRoute
  DashboardInstructorSectionSectionIdRoute: typeof DashboardInstructorSectionSectionIdRoute
  DashboardInstructorStudentStudentIdRoute: typeof DashboardInstructorStudentStudentIdRoute
}

const DashboardInstructorRouteChildren: DashboardInstructorRouteChildren = {
  DashboardInstructorIndexRoute: DashboardInstructorIndexRoute,
  DashboardInstructorSectionSectionIdRoute:
    DashboardInstructorSectionSectionIdRoute,
  DashboardInstructorStudentStudentIdRoute:
    DashboardInstructorStudentStudentIdRoute,
}

const DashboardInstructorRouteWithChildren =
  DashboardInstructorRoute._addFileChildren(DashboardInstructorRouteChildren)

interface DashboardSchoolRouteChildren {
  DashboardSchoolInvoicesRoute: typeof DashboardSchoolInvoicesRoute
  DashboardSchoolSummaryRoute: typeof DashboardSchoolSummaryRoute
  DashboardSchoolIndexRoute: typeof DashboardSchoolIndexRoute
  DashboardSchoolSectionSectionIdRoute: typeof DashboardSchoolSectionSectionIdRoute
  DashboardSchoolStudentStudentIdRoute: typeof DashboardSchoolStudentStudentIdRoute
}

const DashboardSchoolRouteChildren: DashboardSchoolRouteChildren = {
  DashboardSchoolInvoicesRoute: DashboardSchoolInvoicesRoute,
  DashboardSchoolSummaryRoute: DashboardSchoolSummaryRoute,
  DashboardSchoolIndexRoute: DashboardSchoolIndexRoute,
  DashboardSchoolSectionSectionIdRoute: DashboardSchoolSectionSectionIdRoute,
  DashboardSchoolStudentStudentIdRoute: DashboardSchoolStudentStudentIdRoute,
}

const DashboardSchoolRouteWithChildren = DashboardSchoolRoute._addFileChildren(
  DashboardSchoolRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardCmsRoute: typeof DashboardCmsRouteWithChildren
  DashboardForgotPasswordRoute: typeof DashboardForgotPasswordRoute
  DashboardInstructorRoute: typeof DashboardInstructorRouteWithChildren
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardResetPasswordRoute: typeof DashboardResetPasswordRoute
  DashboardSchoolRoute: typeof DashboardSchoolRouteWithChildren
  DashboardSignupRoute: typeof DashboardSignupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardCmsRoute: DashboardCmsRouteWithChildren,
  DashboardForgotPasswordRoute: DashboardForgotPasswordRoute,
  DashboardInstructorRoute: DashboardInstructorRouteWithChildren,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardResetPasswordRoute: DashboardResetPasswordRoute,
  DashboardSchoolRoute: DashboardSchoolRouteWithChildren,
  DashboardSignupRoute: DashboardSignupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmailPreviewRoute: EmailPreviewRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ProjectsRoute: ProjectsRoute,
  SchoolsRoute: SchoolsRoute,
  StudentsRoute: StudentsRoute,
  ApiSendDigestRoute: ApiSendDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
